variable "ami_id" {
  description = "The AMI ID of EC2 that will be launched. Default to Ubuntu 18.04 if left empty"
  type        = string
  default     = ""
}

variable "instance_type" {
  description = "Type of EC2 instance that will be launched"
  type        = string
  default     = "t3a.small"
}

variable "key_name" {
  description = "Keypair name of the EC2. Mutually exclusive with the public_key variable"
  type        = string
  default     = ""
}

variable "aws_access_key_id" {
  description = "Access key for atlantis "
  type        = string
  default     = ""
}

variable "public_key" {
  description = "Public key material that will be used by EC2. If set, will create a new EC2 key pair with autogenerated name"
  default     = ""
}

variable "private_key" {
  description = "Public key material that will be used by EC2. It will be used to run command on new EC2"
  default     = ""
}

variable "tags" {
  description = "Tags that will be added to the EC2 instance"
  type        = map(string)
  default     = {}
}

variable "subnet_id" {
  description = "Subnet ID of the EC2. Will use subnet in default VPC if left empty"
  type        = string
  default     = ""
}

variable "secgroup_id" {
  description = "ID of security group that will be used by EC2. Leave it empty to use default allow ssh, http, and https from anywhere"
  type        = string
  default     = ""
}

variable "attach_admin_policy" {
  description = "Flag to decide whether to attach AdministratorAccess policy to atlantis role"
  type        = bool
  default     = true
}

variable "root_disk_size" {
  description = "Size of the EC2 root disk size in GB"
  type        = number
  default     = 20
}

variable "terraform_version" {
  type    = string
  default = "1.3.6"
}


variable "remote_backend_s3_bucket_name" {
  type    = string
  default = "yury-aws-project-terraform-remote-state"
}

variable "remote_backend_s3_key" {
  type    = string
  default = "aws-project/terraform/live/dev/aws-ec2-atlantis.tfstate"
}

variable "remote_backend_s3_region" {
  type    = string
  default = "us-east-1"
}

variable "github_user" {
  type    = string
  default = "TechBotCI"
}

# variable "github_token" {
#   type = string
#   default = ""
# }

variable "github_repository" {
  type    = string
  default = ""
}

variable "github_webhook_secret" {
  type    = string
  default = ""
}

variable "atlantis_webhook_url" {
  type    = string
  default = ""
}